name: 'Get and install dependencies'
description: 'Get dependencies and get them'
inputs:
  caching:
    description: 'Whether to cache dependencies or not'
    required: false
    default: 'true'
outputs:
  cached-used:
    value: ${{ steps.npn-ci.outputs.cache }}
runs:
  using: 'composite'
  steps:
    - name: print
      run: echo ${{  inputs.caching }}
      shell: bash
    - name: Cache dependencies
      if: inputs.caching == true 
      id: cache
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit == 'false' || inputs.caching == 'true'
      id: npm-ci
      shell: bash
      run: | 
        npm ci
        echo "cache=kurwa" >> $GITHUB_OUTPUT
        echo $GITHUB_OUTPUT