name: 'Test js action'
description: "That's test"
inputs:
  bucket:
    required: true
  region:
    default: 'us-west'
  folder:
    required: true
outputs:
  website-url:
    description: 'web url'
runs:
  using: 'node16'
  main: 'main.js'

