name: hello-matrix
on:
  push:
    branches:
      - main

jobs:
  printer:
    strategy:
      matrix:
        print_val: [157, 23, 1412]
        runner: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.runner}}
    steps:
      - name: fail me
        if: matrix.print_val = 23
        run: exit 1
      - name: print me
        run: echo ${{ matrix.print_val }}
