name: hello-matrix
on:
  workflow_dispatch:
    inputs:
      matrix:
        type: string
        required: true
jobs:
  printer:
    strategy:
      matrix:
        ${{ fromJson( inputs.matrix ) }}
  steps:
    - name: print r0
      run: echo ${{ matrix.r0 }}
    - name: print r1
      run: echo ${{ matrix.r1 }}
     - name: print r2
      run: echo ${{ matrix.r2 }}           