name: hello-matrix
on:
  workflow_call:
    inputs:
      matrix:
        type: string
        required: true
jobs:
  printer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r0: ${{ fromJson(inputs.matrix.r0) }}
        r1: ${{ fromJson(inputs.matrix.r1) }}
        r2: ${{ fromJson(inputs.matrix.r2) }}

    steps:
      - name: print r0
        run: echo ${{ matrix.r0 }}
      - name: print r1
        run: echo ${{ matrix.r1 }}
      - name: print r2
        run: echo ${{ matrix.r2 }}           