name: hello-matrix
on:
  push:
    branches:
      - main

jobs:
  printer:
    uses: ./.github/workflows/reusable.yaml
    secrets: inherit
  impostor:
    runs-on: ubuntu-latest
    steps:
    - name: imposting
      run: |
        echo ${{ secrets.foreign_name }} > file
        cat file
  output-reader:
    runs-on: ubuntu-latest
    needs: printer
    steps:
      - name: echo mate
        run: echo ${{ needs.printer.outputs.worker-message }}
