name: hello-matrix
on:
  push:
    branches:
      - main

jobs:
  printer:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/reusable.yaml
    with:
      my_name: Abra kadabra
    secrets:
      foreign_name: ${{ secrets.foreign_name }}
