name: hello-matrix
on:
  push:
    branches:
      - main

jobs:
  printer:
    continue-on-error: true
    strategy:
      matrix:
        print_val: [157, 23, 1412, 1, 2 ,3 ,4 ,5 ,6,7,8]
        runner: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.runner}}
    steps:
      - name: fail me
        if: matrix.print_val == 157
        run: exit 1
      - name: print me
        run: echo ${{ matrix.print_val }}
